#!groovy

pipeline {
    agent {
        kubernetes {
            yamlFile "ci/pod_builder.yaml"
            retries 0
        }
    }
    environment {
        ECR_REGISTRY = "docker.io/distrolessman"
        IMAGE_NAME = "elearning-zulu-api"
        TAG = "latest"
    }
    stages {
        stage('Build') {
            steps {
                container("builder") {
                    sh "sed -i 's/\\/\\/mavenNexus()/maven { url \"http:\\/\\/192.168.1.4:32081\\/repository\\/maven-central\"\\nallowInsecureProtocol true }/g' build.gradle"
                    sh "sed -i '1ipluginManagement { repositories { maven { url \"http://192.168.1.4:32081/repository/maven-central\"\\nallowInsecureProtocol true }}}' settings.gradle"
                    sh "gradle bootJar -x test -i --stacktrace"
                    sh "cd build/libs && java -Djarmode=layertools -jar e-learning-*.jar extract"
                }
                container("pusher") {
                    sh """#!/busybox/sh
                    /kaniko/executor --context `pwd` \
                        --dockerfile `pwd`/Dockerfile \
                        --destination "${ECR_REGISTRY}/${IMAGE_NAME}:${TAG}" \
                        --use-new-run=true
                    """
                }
            }
        }
    }
}