apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-ci
spec:
  containers:
    - name: builder
      image: docker.io/distrolessman/auto-ci:jre-17.0.8-alpine-3.18
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /root/.m2
          name: maven-cache
    - name: pusher
      image: gcr.io/kaniko-project/executor:debug
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /kaniko/.docker
          name: jenkins-docker-cfg

  volumes:
    - name: maven-cache
      hostPath:
        path: /home/rdteam/.m2
    - name: jenkins-docker-cfg
      projected:
        sources:
          - secret:
              name: docker-credentials
              items:
                - key: .dockerconfigjson
                  path: config.json
